.Dd Feburary 04, 2025
.Dt ACCESSORYSENSORMGRD 8
.Os Darwin
.Sh NAME
.Nm accessorysensormgrd
.Nd Sensor scheduling and Exclave interaction daemon for AirPods and other Audio Accessories
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
accessorysensormgrd daemon will be responsible for scheduling AirPods sensors and interacting with Exclave for data processing to enable intelligent features.
.Sh HISTORY
accessorysensormgrd first appeared in macOS 16.0"
