.Dd January 29, 2024
.Dt UNIFIEDASSETD 8
.Os Darwin
.Sh NAME
.Nm assetsubscriptiond
.Nd Initiates downloads of required files based on the current system configuration.
.Sh SYNOPSIS
.Nm
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION

.Sh HISTORY
.Nm
assetsubscriptiond first appeared in macOS 16.0
