.Dd Feb 6, 2025
.Dt ECOSYSTEMAGENT 8
.Os Darwin
.Sh NAME
.Nm ecosystemagent
.Nd Displays information to the current user on behalf of ecosystemd.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
ecosystemagent will display information to the current user on behalf of ecosystemd.
HISTORY
ecosystemagent first appeared in macOS 16
