.Dd December 07, 2022
.Dt GAMEPOLICYAGENT 8
.Os Darwin
.Sh NAME
.Nm GamePolicyAgent
.Nd Assists gamepolicyd in user optimization of system performance for running game processes, manages UI elements.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Assists gamepolicyd in user optimization of system performance by monitoring currently running games and adjusting system resources.
.Sh HISTORY
GamePolicyAgent first appeared in macOS 14.0.
