.Dd June 10, 2024
.Dt intelligencecontextd 8
.Os Darwin
.Sh NAME
.Nm intelligencecontextd
.Nd This is a daemon that retrieves contextual information from various sources.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
retrieves contexual information from various sources to provide useful information about the user and their device state.
.Sh SEE ALSO
.Xr intelligenceflowd 8
