.Dd June 06, 2022
.Dt knowledgeconstructiond 8
.Os macOS
.Sh NAME
.Nm knowledgeconstructiond
.Nd A daemon that analyzes content on the device to build a general purpose knowledge graph.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
analyzes the content on this device to help build a knowledge graph representing the device and the user. It works together with intelligenceplatformd, performing some of the heavy processing tasks, to generate the knowledge graph.
.Sh SEE ALSO
.Xr intelligenceplatformd 8
