.Dd September 28, 2024
.Dt remotesoftwareupdated 8
.Os Darwin
.Sh NAME
.Nm remotesoftwareupdated
.Nd Remote Software Update daemon
.Sh DESCRIPTION
.Nm
is a daemon that facilities paired devices to perform a remote software update over the network.
.Pp
There are no configuration options to
.Nm .
Users should not run this
.Nm
manually.
