.Dd September 23, 2024
.Dt replicatord 8
.Os "macOS"
.Sh NAME
.Nm replicatord
.Nd remote widget sync daemon
.Sh DESCRIPTION
.Nm
is a daemon that provides data syncing for remote widgets and remote device data for iPhone Mirroring.
.Pp
There are no options for
.Nm , and users should not run
.Nm
manually.
