.\"
.\" Copyright 2023 Apple Inc. All rights reserved.
.\"
.Dd March 9, 2023
.Dt SYSTEM-OVERRIDE 8
.Os macOS
.Sh NAME
.Nm system-override
.Nd configure system overrides
.Sh SYNOPSIS
.Nm
.Ar command
.Sh DESCRIPTION
.Nm
modifies system overrides.  Some of the commands
require the device to be booted into the Recovery OS.  Invoke
.Nm
with no arguments to see a full usage statement.

