.Dd 7/24/2024               \" DATE
.Dt usbnotificationagent 8  \" Program name and manual section number
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify
.Nm usbnotificationagent
.Nd Agent to detect accessory issues and present a notification to the active user
.Sh DESCRIPTION          \" Section Header - required - don't modify
Use
.Xr launchctl 1
to control
.Nm
.Sh PREFERENCES
To reset suppressed notifications use
.Xr defaults 1
to modify the com.apple.usbnotificationagent domain.
.
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.It Pa /System/Library/LaunchAgents/com.apple.usbnotificationagent.plist
.It Pa /System/Library/Sandbox/Profiles/com.apple.usbnotificationagent.sb
.El                      \" Ends the list
.Sh SEE ALSO
.Xr launchd 1
.Xr launchctl 1
.Xr defaults 1
