.Dd August 28, 2023
.Dt PRIVATECLOUDCOMPUTED 8
.Os Darwin
.Sh NAME
.Nm privatecloudcomputed
.Nd private cloud compute offload daemon
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Handles encrypting and sending requests to validated cloud compute nodes
.Sh HISTORY
First appeared in macOS 15
