.Dd January 25, 2022
.Dt MOBILETIMERD 8
.Os Darwin
.Sh NAME
.Nm mobiletimerd
.Nd timer agent
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
It manages alarms and timers, and is responsible for showing notifications when they fire.
.Sh HISTORY
mobiletimerd first appeared in macOS 13.
