.Dd February 9, 2022
.Dt MTLASSETUPGRADERD 8
.Os Darwin
.Sh NAME
.Nm MTLAssetUpgraderD
.Nd Metal asset upgrader daemon
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
MTLAssetUpgraderD performs background compilation of binary archives to target the current GPU architecture/OS.
.Sh HISTORY
mtlregistrationd first appeared in macOS 13.0 and iOS 16.0
