.\""Copyright (c) 2018-2022 Apple Inc. All Rights Reserved.
.Dd 1/11/14
.Dt cloudpaird 1
.Os "Mac OS X"
.Sh NAME
.Nm cloudpaird
.Nd cloudpaird daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a daemon.
.Pp
There are no configuration options to \fBcloudpaird\fR.  Users should not run it manually.
