.Dd June 10, 2022
.Dt mdmclient 1
.Os MacOSX
.Sh NAME
.Nm mdmclient
.Nd MDM (Mobile Device Management) client
.Pp
.Sh DESCRIPTION
.Nm
.Pp
Used internally for communication with Mobile Device Management server. Receives profiles and commands from the server after a user enrolls with the server by installing a management profile. Provides support for configuration profiles. Part of Managed Client (MCX).

WARNING: All command arguments are private. The arguments and output can and will change without notice. Do not rely on any output this command may produce.
