.Dd 4/21/22
.Dt transparency-sysdiagnose 1
.Os Darwin
.Sh NAME
.Nm transparency-sysdiagnose
.Nd sysdiagnose information for transparency project
.Sh SYNOPSIS
.Nm gathers sysdiagnose information for transparency
.Sh DESCRIPTION
Gathers sysdiagnose information for transparency
.Sh SEE ALSO
.Xr a transparencyd
