.TH "MPSCNNConvolution.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSCNNConvolution.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSCNNNormalization\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSCNNNeuronType\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSCNNNeuron\&.h>\fP
.br
\fC#include <MPSCore/MPSState\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSNNGradientState\&.h>\fP
.br
\fC#include <simd/simd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSCNNConvolutionDescriptor\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSubPixelConvolutionDescriptor\fP"
.br
.ti -1c
.RI "class \fBMPSCNNDepthWiseConvolutionDescriptor\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionGradientState\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionWeightsAndBiasesState\fP"
.br
.ti -1c
.RI "protocol \fB<MPSCNNConvolutionDataSource >\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolution\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNFullyConnected\fP"
.br
.ti -1c
.RI "class \fBMPSCNNFullyConnectedGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionTranspose\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBinaryConvolution\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBinaryFullyConnected\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef NSArray< \fBMPSCNNConvolutionGradientState\fP * > \fBMPSCNNConvolutionGradientStateBatch\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMPSCNNConvolutionGradientOption\fP { \fBMPSCNNConvolutionGradientOptionGradientWithData\fP, \fBMPSCNNConvolutionGradientOptionGradientWithWeightsAndBias\fP, \fBMPSCNNConvolutionGradientOptionAll\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef NSArray<\fBMPSCNNConvolutionGradientState\fP*> \fBMPSCNNConvolutionGradientStateBatch\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMPSCNNConvolutionGradientOption\fP"
Options used to control which gradient to compute 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMPSCNNConvolutionGradientOptionGradientWithData \fP\fP
.TP
\fB\fIMPSCNNConvolutionGradientOptionGradientWithWeightsAndBias \fP\fP
.TP
\fB\fIMPSCNNConvolutionGradientOptionAll \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
