.TH "MPSCNNMath.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSCNNMath.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSCNNArithmeticGradientState\fP"
.br
.ti -1c
.RI "class \fBMPSCNNArithmetic\fP"
.br
.ti -1c
.RI "class \fBMPSCNNAdd\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSubtract\fP"
.br
.ti -1c
.RI "class \fBMPSCNNMultiply\fP"
.br
.ti -1c
.RI "class \fBMPSCNNDivide\fP"
.br
.ti -1c
.RI "class \fBMPSCNNArithmeticGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNAddGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSubtractGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNMultiplyGradient\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef NSArray< \fBMPSCNNArithmeticGradientState\fP * > \fBMPSCNNArithmeticGradientStateBatch\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef NSArray<\fBMPSCNNArithmeticGradientState\fP*> \fBMPSCNNArithmeticGradientStateBatch\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
