.TH "MPSCNNNeuron.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSCNNNeuron.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNNeuronType\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSNNNeuronDescriptor\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuron\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronLinear\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronReLU\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronPReLU\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronSigmoid\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronHardSigmoid\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronTanH\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronAbsolute\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronSoftPlus\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronSoftSign\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronELU\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronReLUN\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronPower\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronExponential\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronLogarithm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
