.TH "MPSCNNBatchNormalization.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSCNNBatchNormalization.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSCNNNormalizationWeights\&.h>\fP
.br
\fC#include <MPSCore/MPSState\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSCNNBatchNormalizationState\fP"
.br
.ti -1c
.RI "protocol \fB<MPSCNNBatchNormalizationDataSource >\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBatchNormalization\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBatchNormalizationStatistics\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBatchNormalizationGradient\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBatchNormalizationStatisticsGradient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
