.TH "MPSCNNInstanceNormalization.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSCNNInstanceNormalization.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSCNNNormalizationWeights\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSCNNInstanceNormalizationGradientState\fP"
.br
.ti -1c
.RI "protocol \fB<MPSCNNInstanceNormalizationDataSource >\fP"
.br
.ti -1c
.RI "class \fBMPSCNNInstanceNormalization\fP"
.br
.ti -1c
.RI "class \fBMPSCNNInstanceNormalizationGradient\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef NSArray< \fBMPSCNNInstanceNormalizationGradientState\fP * > \fBMPSCNNInstanceNormalizationGradientStateBatch\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef NSArray<\fBMPSCNNInstanceNormalizationGradientState\fP*> \fBMPSCNNInstanceNormalizationGradientStateBatch\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
