.TH "MPSCNNLoss.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSCNNLoss.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNTypes\&.h>\fP
.br
\fC#import <MPSCore/MPSState\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSCNNLossDataDescriptor\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLossLabels\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLossDescriptor\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLoss\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef NSArray< \fBMPSCNNLossLabels\fP * > \fBMPSCNNLossLabelsBatch\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef NSArray<\fBMPSCNNLossLabels\fP*> \fBMPSCNNLossLabelsBatch\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
