.TH "MPSImageReduce.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSImageReduce.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSImage/MPSImageKernel\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSImageReduceUnary\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceRowMin\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceColumnMin\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceRowMax\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceColumnMax\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceRowMean\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceColumnMean\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceRowSum\fP"
.br
.ti -1c
.RI "class \fBMPSImageReduceColumnSum\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
