.TH "MPSMatrix.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSMatrix.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSMatrix/MPSMatrixTypes\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixMultiplication\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixSolve\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixDecomposition\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixCombination\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixSoftMax\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixFindTopK\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
