.TH "MPSMatrixFullyConnected.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSMatrixFullyConnected.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSNeuralNetwork/MPSCNNNeuronType\&.h>\fP
.br
\fC#include <MPSMatrix/MPSMatrix\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSMatrixFullyConnected\fP"
.br
.ti -1c
.RI "class \fBMPSMatrixNeuron\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
