.TH "MPSMatrixSoftMax.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSMatrixSoftMax.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSCore/MPSKernel\&.h>\fP
.br
\fC#import <MPSMatrix/MPSMatrixTypes\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSMatrixSoftMax\fP"
.br
.ti -1c
.RI "class \fBMPSMatrixLogSoftMax\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
