.TH "MPSNNGraphNodes.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSNNGraphNodes.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSCore/MPSImage\&.h>\fP
.br
\fC#include <MPSCore/MPSState\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSNeuralNetworkTypes\&.h>\fP
.br
\fC#include <MPSNeuralNetwork/MPSCNNNeuronType\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "protocol \fB<MPSHandle >\fP"
.br
.ti -1c
.RI "protocol \fB<MPSNNTrainableNode >\fP"
.br
.ti -1c
.RI "class \fBMPSNNImageNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNStateNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNGradientStateNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionGradientStateNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNBinaryGradientStateNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNArithmeticGradientStateNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNFilterNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNGradientFilterNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNFullyConnectedNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBinaryConvolutionNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBinaryFullyConnectedNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionTransposeNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNConvolutionGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronAbsoluteNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronELUNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronReLUNNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronLinearNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronReLUNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronSigmoidNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronHardSigmoidNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronSoftPlusNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronSoftSignNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronTanHNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronPReLUNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronPowerNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronExponentialNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronLogarithmNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNeuronGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingAverageNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingL2NormNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingMaxNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNDilatedPoolingMaxNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingMaxGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingAverageGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNPoolingL2NormGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNDilatedPoolingMaxGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNNormalizationNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSpatialNormalizationNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSpatialNormalizationGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLocalContrastNormalizationNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLocalContrastNormalizationGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNCrossChannelNormalizationNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNCrossChannelNormalizationGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNInstanceNormalizationNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNInstanceNormalizationGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBatchNormalizationNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNBatchNormalizationGradientNode\fP"
.br
.ti -1c
.RI "protocol \fB<MPSImageTransformProvider >\fP"
.br
.ti -1c
.RI "class \fBMPSNNScaleNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNBilinearScaleNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNLanczosScaleNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNBinaryArithmeticNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNAdditionNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNSubtractionNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNMultiplicationNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNDivisionNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNArithmeticGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNAdditionGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNSubtractionGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNMultiplicationGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNDropoutNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNDropoutGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNLabelsNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLossNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNConcatenationNode\fP"
.br
.ti -1c
.RI "class \fBMPSNNConcatenationGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSoftMaxNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNSoftMaxGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLogSoftMaxNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNLogSoftMaxGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNUpsamplingNearestNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNUpsamplingBilinearNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNUpsamplingNearestGradientNode\fP"
.br
.ti -1c
.RI "class \fBMPSCNNUpsamplingBilinearGradientNode\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
