.TH "MPSNNGradientState.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSNNGradientState.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSCore/MPSState\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSNNGradientState\fP"
.br
.ti -1c
.RI "class \fBMPSNNBinaryGradientState\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef NSArray< \fBMPSNNGradientState\fP * > \fBMPSNNGradientStateBatch\fP"
.br
.ti -1c
.RI "typedef NSArray< \fBMPSNNBinaryGradientState\fP * > \fBMPSNNBinaryGradientStateBatch\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef NSArray<\fBMPSNNBinaryGradientState\fP *> \fBMPSNNBinaryGradientStateBatch\fP"

.SS "typedef NSArray<\fBMPSNNGradientState\fP *> \fBMPSNNGradientStateBatch\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
