.TH "MPSNeuralNetwork.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSNeuralNetwork.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSNeuralNetwork/MPSNeuralNetworkTypes\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNConvolution\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNPooling\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNLoss\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNMath\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNNormalization\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNSoftMax\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNUpsampling\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNBatchNormalization\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNInstanceNormalization\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSCNNDropout\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSRNNLayer\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSMatrixLayer\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSNNReduce\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSNNReshape\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSNNSlice\&.h>\fP
.br
\fC#import <MPSNeuralNetwork/MPSNNGraph\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
