.TH "MPSNNReduce.h" 3 "Thu Feb 8 2018" "Version MetalPerformanceShaders-100" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSNNReduce.h
.SH SYNOPSIS
.br
.PP
\fC#include <MPSNeuralNetwork/MPSCNNKernel\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSNNReduceUnary\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceRowMin\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceColumnMin\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceFeatureChannelsMin\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceRowMax\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceColumnMax\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceFeatureChannelsMax\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceRowMean\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceColumnMean\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceFeatureChannelsMean\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceRowSum\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceColumnSum\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceFeatureChannelsSum\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceBinary\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceFeatureChannelsAndWeightsMean\fP"
.br
.ti -1c
.RI "class \fBMPSNNReduceFeatureChannelsAndWeightsSum\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
