.TH "MPSState.h" 3 "Thu Jul 13 2017" "Version MetalPerformanceShaders-87.2" "MetalPerformanceShaders.framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MPSState.h
.SH SYNOPSIS
.br
.PP
\fC#import <MPSCore/MPSCoreTypes\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMPSState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MetalPerformanceShaders\&.framework from the source code\&.
