.Dd October 28, 2021
.Dt APPLEVIRTUALPLATFORMHIDBRIDGE 8
.Os Darwin
.Sh NAME
.Nm AppleVirtualPlatformHIDBridge
.Nd Bridge HID services from a Virtualization host
.Sh SYNOPSIS
.Nm
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
When macOS is running as a guest operating system in a virtual machine created by the Virtualization framework
and configured with an AppleVirtualPlatformHIDBridge device,
.Nm
instantiates and manages virtual input devices on behalf of the host.
.Sh HISTORY
AppleVirtualPlatformHIDBridge first appeared in macOS 13.
