.\""Copyright (c) 2021 Apple Inc. All Rights Reserved.
.Dd 2/11/13
.Dt coordinated 8
.Os "Mac OS X"
.Sh NAME
.Nm coordinated
.Nd Coordination Daemon.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a per-user daemon which supports cross device features.
.Pp
There are no configuration options to \fBcoordinated\fR.  Users should not run
.Nm
manually.

