.Dd December 07, 2022
.Dt GAMEPOLICYD 8
.Os Darwin
.Sh NAME
.Nm gamepolicyd
.Nd Optimizes system performance for running game processes.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Optimizes system performance by monitoring currently running games and adjusting system resources.
.Sh HISTORY
gamepolicyd first appeared in macOS 14.0.
