.Dd January 11, 2023
.Dt HOMEENERGYD 8
.Os Darwin
.Sh NAME
.Nm homeenergyd
.Nd Home Energy Daemon
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
homeenergyd is a daemon that manages home energy and its interaction with Home
.Sh HISTORY
homeenergyd first appeared in macOS 14.0
