.Dd October 8, 2021
.Dt backgroundassetsd 8
.Os Mac OS X
.\"                                                                                NAME
.Sh NAME
.Nm backgroundassetsd
.Nd helper for the BackgroundAssets framework.
.\"                                                                                SYNOPSIS
.Sh SYNOPSIS
.Nm
.\"                                                                                DESCRIPTION
.Sh DESCRIPTION
.Nm
is used by the BackgroundAssets framework for keeping track of the state of background downloads request by application clients. This process is also resposible for relay that state to its client application when the state of their background download changes. It is not meant to be invoked directly.
