.Dd Dec 14, 2021
.Dt backgroundtaskmanagementd 8
.Os macOS
.
.Sh NAME
.Nm backgroundtaskmanagementd
.Nd Daemon which manages policy for background task processes and login items.
.
.Sh DESCRIPTION
.Nm
is a daemon that manages a set of items which are intended to run as background tasks or at login, and the policy pertaining to the user approval for allowing execution.
This includes items in System Preferences > Users & Groups > Login Items, items installed with ServiceManagement, and items from managed device profiles.
.
.Sh FILES
/System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/backgroundtaskmanagementd
/System/Library/LaunchDaemons/com.apple.backgroundtaskmanagementd.plist
.Pp
/var/db/backgroundtaskmanagement
.
.Sh SEE ALSO
.Nm btmtool
.
