.Dd October 05, 2021
.Dt COUNTRYD 8
.Os Darwin
.Sh NAME
.Nm countryd
.Nd Listens for country-level information and makes that available to users of RegulatoryDomain.framework
.Sh SYNOPSIS
Takes no arguments, and should not be launched manually.
.Sh DESCRIPTION
Receives country code updates from user location, mobile country code (when available) and nearby 802.11d wifi access points. This information is then stored in a cache and used to compute a country code estimate which combines both the on-device code computed from local sensors, and answers about which country nearby devices believe they are in.
.Sh HISTORY
countryd first appeared in macOS 13
