.Dd July 28, 2022
.Dt GPUTOOLSSERVICED 8
.Os Darwin
.Sh NAME
.Nm gputoolsserviced
.Nd provides services for the GPU Debugger
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
.Nm
is an OS user agent that advertises services for use by the GPU Debugger.
.Sh HISTORY
.Nm
first appeared in macOS 14.0 and iOS 17.0.
