.\"
.\" Copyright (c) 2006-2023 Apple Inc. All rights reserved.
.\"
.Dd January 1, 2023
.Dt stickersd 8
.Os "macOS"
.Sh NAME
.Nm stickersd
.Nd stickersd daemon
.Sh DESCRIPTION
.Nm stickersd
manages user-created and recently-used stickers. It provides functionality to apps using
the Stickers API and performs various background maintenance tasks.
.Pp
This command is not intended to be invoked directly.
