.\" Copyright (c) 2022 Apple Inc. All rights reserved.
.Dd 5 Oct, 2022
.Dt transparencyStaticKey 8
.Os Darwin
.Sh NAME
.Nm transparencyStaticKey
.Nd The transparency static key pinning daemon.
.Sh DESCRIPTION
.Nm
transparencyStaticKey handles the pinning setup flow for Messages.
It is not intended to be invoked directly.
.Sh SEE ALSO
.Xr launchd 8
.Xr launchd.conf 5
