.Dd 1/5/24
.Dt avbanalyse 1
.Os Darwin
.Sh NAME
.Nm avbanalyse
.Nd Audio Video Bridging analysis tool.
.Sh SYNOPSIS
.Nm
command
<arguments>
.Sh DESCRIPTION
The
.Nm
executable is used for analysis of PCAP network captures and test data for AVB testing.
.sp
.Pp
The following commands are available:
.Bl -tag -width -a
.It pcap
Parse a pcapng file and extract the AVTP audio stream media clocking and gPTP clocking for analysis.
.It trace
Parse an Apple Trace (atrc) file and extract AVB tracepoint data for analysis.
.El
.sp
.Pp
The following options are available for the pcap command:
.Bl -tag -width -a
.It --data pcap-path
The path to the pcap file to be analysed.
.It --output path
Specifies the path to the directory to put all of the output data from the analysis. Creates the directory if it does not exist.
.It [--extract-payload]
Extract the payload contents into a file for playback. Only applies to IEC 61883-6 AM824 and AAF PCM Audio streams.
.It [--tdev-analysis]
Run TDEV analysis on the extracted media clock of the stream.
.El
.Pp
The following options are available for the trace command:
.Bl -tag -width -a
.It --data trace-path
The path to the trace file to be analysed.
.It --output path
Specifies the path to the directory to put all of the output data from the analysis. Creates the directory if it does not exist.
.El
