.Dd June 2, 2020
.Dt CRYPTEXCTL-DETACH 1
.Os Darwin
.Sh NAME
.Nm cryptexctl detach
.Nd detach a device
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
detach
.Ar DEV-NODE
.Sh DESCRIPTION          \" Section Header - required - don't modify
Detach a device node that was created from a disk image. Any sub-device
identifier may be given, and the primary device will be discovered and detached
.Po e.g. passing
.Qq Pa /dev/disk4s24s83
will detach
.Pa /dev/disk4
.Pc .
Either a name or complete
.Xr devfs 5
path may be provided.
.Sh OPTIONS
List of flags and their descriptions:
.Bl -tag -width -indent
.It Ar DEV-NODE
The device to detach
.El
.Sh SEE ALSO
.Xr cryptexctl 1 ,
.Xr devfs 5 ,
.Xr cryptexd 8
.Sh HISTORY
Introduced in macOS 11.0
