.Dd January 29, 2024
.Dt VIEWDIAGNOSTIC 1
.Os
.Sh NAME
.Nm viewdiagnostic
.Nd Visualize diagnostic reports
.Sh SYNOPSIS
.Nm viewdiagnostic
.Ar path
.Sh DESCRIPTION
.Nm viewdiagnostic
translates crash reports and other diagnostic reports into a textual representation for improved visualization.
Tools that parse data from the report should use its as-written format instead.
