.\""Copyright (c) 2022 Apple Inc. All Rights Reserved.
.Dd $Mdocdate$
.Dt SHAZAM-CUSTOM-CATALOG-DISPLAY 1
.Os

.Sh NAME
.Nm shazam custom-catalog display
.Nd Display contents of a custom catalog file

.Sh SYNOPSIS
.Nm
.Op Fl \-input Ar input


.Sh DESCRIPTION
.Pp
Use this command to display the contents of an existing custom catalog file. Each signature and media items entry is displayed to offer information about the contents of a custom catalog file. See
.Cm shazam-custom-catalog-create(1)
for information on how to create a custom catalog file.

.Sh OPTIONS
.Bl -tag -width indent

.It Fl i,--input Ar input
Path to an existing custom catalog file to be displayed.

.Sh SEE ALSO
.Sy shazam-custom-catalog-create(1), shazam-custom-catalog-export(1), shazam-custom-catalog-remove(1)

.Sh NOTES
.Bl -enum
.It
ShazamKit Documentation
.Bd -literal -compact
https://developer.apple.com/shazamkit
.El
