.\""Copyright (c) 2023 Apple Computer, Inc. All Rights Reserved.
.Dd September 20th, 2023
.Dt DUETEXPERTD 8
.Os "Mac OS X"
.Sh NAME
.Nm duetexpertd
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
powers personalized system experiences.
.Pp
There are no configuration options for this service. Users should not run
.Nm 
manually.
