.Dd May 25, 2023
.Dt ecosystemanalyticsd 8
.Os macOS
.Sh NAME
.Nm ecosystemanalyticsd
.Nd Analyzes which frameworks and APIs are used by 3rd party applications
.Sh DESCRIPTION
.Nm
analyzes 3rd party applications to determine API usage.
The reports are used by Apple to improve its products.
Users who need support should use http://www.apple.com/support or other authorized support channels.
Developers who are ADC members should report bugs using Feedback Assistant.app in order to allow for two way communication between Apple and the bug reporter.
