.Dd June 22, 2023
.Dt idleassetsd 8
.Os macOS
.\"																				NAME
.Sh NAME
.Nm idleassetsd
.Nd helper for the TVIdleServices framework.
.\"																				SYNOPSIS
.Sh SYNOPSIS
.Nm
.\"																				DESCRIPTION
.Sh DESCRIPTION
.Nm
is used by the TVIdleServices framework for asset downloading and privileged operations. It is used by various clients in macOS. It is not meant to be invoked directly.
