.Dd June 10, 2024
.Dt intelligenceflowd 8
.Os macOS
.Sh NAME
.Nm intelligenceflowd
.Nd A daemon that manages sessions for intelligence services.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
manages sessions, communication, and state between clients and backend intelligence services.
.Sh SEE ALSO
.Xr intelligencecontextd 8
