.Dd June 06, 2022
.Dt intelligenceplatformd 8
.Os macOS
.Sh NAME
.Nm intelligenceplatformd
.Nd A daemon that analyzes content on the device to build and query a general purpose knowledge graph.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
analyzes the content, along with knowledgeconstructiond, on this device to build a knowledge graph representing the device and the user. Other components of the operating system can query the knowledge graph through intelligenceplatformd to provide richer experiences to the user.
.Sh SEE ALSO
.Xr knowledgeconstructiond 8
