.Dd March 09, 2017
.Dt osanalyticshelper 8
.Os macOS
.Sh NAME
.Nm osanalyticshelper
.Nd Helper process for analytics and diagnostics
.Sh DESCRIPTION
.Nm
supports writing and reporting analytics and diagnostics.
The reports are used by Apple to improve its products.
Users who need support should use http://www.apple.com/support or other authorized support channels.
Developers who are ADC members should report bugs using http://bugreporter.apple.com in order to allow for two way communication between Apple and the bug reporter.
.Sh SEE ALSO
.Xr SubmitDiagInfo 8
