.\""Copyright (c) 2010-2024 Apple Computer, Inc. All Rights Reserved.
.Dd September 1, 2010
.Dt TALAGENT 8  
.Os "macOS"       
.Sh NAME
.Nm talagentd
.Nd helper agent for application lifecycle features
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
daemon provides services related to the Transparent App Lifecycle feature.
.Pp
Users should not run
.Nm
manually.
