.\""Copyright (c) 2022 Apple inc. All Rights Reserved.
.Dd 2022
.Dt AUDIOANALYTICSD 8
.Os Darwin
.Sh NAME
.Nm audioanalyticsd
.Nd Audio Diagnostics and Usage Reporting
.Sh DESCRIPTION
.Nm
is a launch agent that aggregates and analyzes audio usage data for users that have opted in for reporting.
.Pp
There are no configuration options to
.Nm , and users should not run
.Nm
manually.
.
.Pp

