.Dd August 16, 2024
.Dt HISTORICALAUDIOD 8
.Os Darwin
.Sh NAME
.Nm historicalaudiod
.Nd historicalaudiod is a daemon used for Core Audio related purposes. 
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
historicalaudiod is a daemon used for Core Audio related purposes.
.Sh SEE ALSO
.Xr coreaudiod 8 ,
.Sh HISTORY
historicalaudiod first appeared in macOS 15.4
