.Dd October 19, 2021
.Dt RETIMERD 8
.Os Darwin
.Sh NAME
.Nm retimerd
.Nd Apple Type-C Retimer daemon
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Manages background activities for Apple Type-C Retimer
.Sh HISTORY
First appeared in macOS 12.3 and iOS 15.4.
