.\""Copyright (c) 2022 Apple Computer, Inc. All Rights Reserved.
.Dd July 17, 2022
.Dt dataaccessd 8  
.Os macOS
.Sh NAME
.Nm dataaccessd
.Nd calendar sync process
.Sh DESCRIPTION
.Nm
is the calendar sync process. It is used by the system to sync calendar data with calendar servers.
.Pp
There are no configuration options to
.Nm , and users should not run 
.Nm  
manually.
