.Dd July 22, 2022
.Dt IPERF3-DARWIN 1
.Os Darwin
.Sh NAME
.Nm iperf3-darwin
.Nd perform network throughput tests
.Sh SYNOPSIS
.Nm
.Fl s
.Op options
.Nm
.Fl c Ar server
.Op options
.Nm
.Fl h
.Nm
.Fl v
.Sh DESCRIPTION
The
.Nm
is a tool for performing network throughput measurements based on the ESnet iperf3 project
that has been modified to use functionalities specific to Darwin.
.Pp
For a full list of options see:
.Pp
.Bd -ragged -offset indent -compact
.Nm
.Fl h
.Ed
.Sh AUTHORS
A list of the contributors to iperf3 can be found within the
documentation located at
https://software.es.net/iperf/dev.html#authors.
.Sh SEE ALSO
https://software.es.net/iperf
