.Dd May 28, 2024
.Dt USBCTelemetryD 8
.Os Darwin
.Sh NAME
.Nm usbctelemetryd
.Nd Daemon used for collecting USB Type-C Analytics
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Captures various data relating to USB Power Delivery, Thunderbolt, and USB Type-C
.Sh HISTORY
usbctelemetryd first appeared in  MacOS 15.0
