.\" Copyright (c) 2018 Apple Inc. All rights reserved.
.Dd 27 November, 2018
.Dt esctl 1
.Os Darwin
.Sh NAME
.Nm esctl
.Nd control interface for ES OS components and interface to
.Nm endpointsecurityd
daemon
.Sh DESCRIPTION
.Nm
interfaces with
.Nm endpointsecurityd
to manage and inspect registered ES clients.
.Sh SEE ALSO
.Xr EndpointSecurity 7
