.\" Copyright (c) 2016 Apple Inc. All rights reserved.
.Dd 8 January, 2016
.Dt libEndpointSecurity 3
.Os Darwin
.Sh NAME
.Nm libEndpointSecurity
.Nd Endpoint Security library
.Sh DESCRIPTION
.Nm
exports interfaces for operating within the ES subsystem
.Sh SEE ALSO
.Xr EndpointSecurity 7 ,
.Xr endpointsecurityd 8 ,
.Xr esctl 1
