.\" Copyright (c) 2018 Apple Inc. All rights reserved.
.Dd 27 November, 2018
.Dt EndpointSecurity 7
.Os Darwin
.Sh NAME
.Nm EndpointSecurity
.Nd APIs for applications to provide system security policy
.Sh DESCRIPTION
The
.Nd
subsystem is a set of functionality to expose security relevant kernel
events to applications running in user space.
.Sh SEE ALSO
.Xr libdz 3 ,
.Xr dzd 8 ,
.Xr dzctl 1
