.Dd September 1, 2021
.Dt photosctl 1
.Os Mac OS X
.Sh NAME
.Nm photosctl
.Nd Photo Library diagnostic, configuration and test utility
.Sh SYNOPSIS
.Nm
.Op Fl h|--help
.Op Fl -version
.Op Ar <command> ...
.Sh DESCRIPTION
.Nm
supports various diagnostic, configuration, test and other operations on Photo Libraries.
.Pp
Use the special 
.Ar list
command to list all modern commands.
.Pp
Modern
.Nm
.Ar commands
can support options: use the
.Ar help 
or
.Ar usage 
command with a 
.Ar command
to see what options are available for that
.Ar command.
.Pp
Most newer 
.Ar commands
operate on a Photo Library.
These
.Ar commands
all support the option
.Ar --library <path>,
will try the 
.Ar PHOTOSCTL_LIBRARY
environment variable or will operate on the System Photo Library if one is set.
.Pp
Legacy commands operate only on the
.Ar System Photo Library.
Show usage for legacy commands with
.Ar usage legacy
command.
.Sh OPTIONS
.Bl -tag -width flag
.It Fl h|--help
Convenience alias for 
.Ar help,
.
.It Fl -version
Show the version of 
.Nm .
