.Dd January 11th, 2024
.Dt XPROTECT 1
.Os
.Sh NAME
.Nm xprotect
.Nd Utility for interacting with XProtect
.Sh SYNOPSIS
.Nm
.Ar <subcommand>
      
.Sh DESCRIPTION
.Nm
is used to interact with XProtect. It is useful for administrators or users who want to manually invoke XProtect
functionality.

.Pp
.Nm
requires exactly one
.Ar subcommand
option to determine what action is to be performed.

.Sh SUBCOMMANDS
The subcommands are as follows:
.Bl -tag -width indent
.It Sy update
Performs an update of XProtect assets.

.It Sy check [--json]
Prints the currently online available update version.

.It Sy version [--json]
Prints the version of the currently installed XProtect assets.

.It Sy logs
Display XProtect logs.

.It Sy status [--json]
Prints the current status of XProtect.

.It Sy help
Print help for the particular subcommand.

.Sh SEE ALSO
.Xr syspolicyd 8 ,
.Xr spctl 8 ,
.Xr syspolicy_check 1
