.Dd 1/5/24
.Dt avbcapture 1
.Os Darwin
.Sh NAME
.Nm avbcapture
.Nd Audio Video Bridging traffic capture tool.
.Sh SYNOPSIS
.Nm
command
<arguments>
.Sh DESCRIPTION
The
.Nm
executable is used for capturing a PCAPNG file containing gPTP and AVTP stream packets.
.sp
.Pp
The following options are available for the pcap command:
.Bl -tag -width -a
.It --interface bsd-name
The interface to capture traffic on. This option may be provided multiple times to capture simultaneously from multiple interfaces to the one file.
.It --output path
Specifies the path to the PCAPNG file to put all the captured traffic.
.It --ring
Use a ring of packets and only output to file when the capture is stopped.
.It --length num-packets
The number of packets to keep in the ring. Defaults to 2,561,000 if not specified.
.It --allow-tap
Allow the tool to tap the receive queue rather than adding a stream capture allowing capture on a live system. This could potentially cause performance issues resulting in packets being lost.
.It --force-tap
Force using the receive queue rather than adding a stream capture allowing capture on a live system. This could potentially cause performance issues resulting in packets being lost.
.El
