.Dd 3 Feburary, 2023
.Dt cryptexctl-path 1
.Os Darwin
.Sh NAME
.Nm cryptexctl path
.Nd return search paths for a session
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm cryptexctl path
.Op Fl -cryptex Ar BUNDLE_ID
.Fl -path
.Nm cryptexctl path
.Op Fl -cryptex Ar BUNDLE_ID
.Fl -search-path Ar SEARCH_PATH
.Sh DESCRIPTION
cryptexctl path is used to generate search paths for content from cryptexes for the user calling it.
.Sh OPTIONS
A list of options with their descriptions.

.Bl -tag
.It Fl c | Fl -cryptex Ar BUNDLE_ID
Limits results to the cryptex with the specified Bundle ID.
.It Fl s | Fl -session
Specifies the UUID of the session you want to search instead of the current user.
.It Fl S | Fl -search-path Ar SEARCH_PATH
Provided a colon delimited list of paths, returns all instances of those subpaths within applicable cryptexes.
-S /usr:/Library:/invalid
.It Fl p | Fl -path
Use a default SEARCH_PATH appropriate for inserting into the PATH environment variable.
.El
.Sh SEE ALSO
.Xr cryptexctl 1 ,
.Xr cryptexctl-session 1 ,
.Xr cryptex 5 ,
.Sh HISTORY
Introduced in macOS 13.5
