.Dd June 9, 2020
.Dt CRYPTEXCTL-UNINSTALL 1
.Os Darwin
.Sh NAME
.Nm cryptexctl uninstall
.Nd uninstall a cryptex
.Sh SYNOPSIS
.Nm
uninstall
.Op Fl i | -immediate
.Ar CRYPTEX-IDENTIFIER
.Sh DESCRIPTION
Uninstall the cryptex identified by
.Ar CRYPTEX-IDENTIFIER .
A list of installed cryptexes and their identifiers can be
retrieved via
.Xr cryptexctl-list 1 .
.Pp
When a cryptex is uninstalled
.Xr cryptexd 8
will attempt to dispose of any services that were loaded
from the cryptex and unmount the disk image.
Complete uninstallation requires a
reboot to ensure all processes are killed and all files
are no longer in use before
.Xr cryptexd 8
can safely finish the uninstallation.
.Sh OPTIONS
.Bl -tag -width -indent
.It Fl i | -immediate
Force physical uninstalltion to happen immediately if possible.
Normally uninstallation does not take full effect until the next
reboot. This option will attempt to dispose of services loaded
from the cryptex and unmount the disk image. Note that even
if the disk image is unmounted successfully, there is no
guarantee that all services from the cryptex have been disposed
of. Exercise caution with this option.
.It Ar CRYPTEX-IDENTIFIER
The identifier of the cryptex to uninstall. This is the same
identifier used by
.Xr cryptexctl-install 1
to install the cryptex and listed by
.Xr cryptexctl-list 1 .
.El
.Sh SEE ALSO
.Xr cryptexctl-install 1 ,
.Xr cryptexctl-list 1 ,
.Xr cryptexd 8
.Sh HISTORY
Introduced in macOS 11.0
