.Dd August 7, 2020
.Dt CRYPTEXCTL-IDENTITY 1
.Os Darwin
.Sh NAME
.Nm cryptexctl identity
.Nd print the host's personalization identity
.Sh SYNOPSIS
.Nm
identity
.Sh DESCRIPTION
Query and fetch the host's personalization identity. The identifiers displayed
by this command uniquely identify the host.
.Pp
These identifiers can be used with
.Xr cryptexctl-create 1
to personalize a cryptex for a device when the device is not present.
.Sh ENVIRONMENT
.Bl -tag -width CRYPTEX_UDID
.It Ev CRYPTEXCTL_UDID
Read by
.Nm
to set the
.Fl --udid
option on the base
.Xr cryptexctl 1
command. This UDID value can be retrieved from the
.Xr cryptexctl-device 1
command's
.Em list
or
.Em print
actions and provides a convenient way to operate on a
single device when multiple devices are connected.
.Pp
The magic value
.Qq first
will select the first discovered device.
.El
.Sh TROUBLESHOOTING
This command will communicate with the local cryptex subsystem if
.Fl -udid
or
.Ev CRYPTEXTCTL_UDID
is not specified. When manually personalizing a cryptex with
.Xr cryptexctl-create 1
ensure you are communicating with the device you expect by confirming the
.Dv UDID
matches with the output from
.Xr cryptexctl-device 1 .
.Sh SEE ALSO
.Xr cryptexctl 1 ,
.Xr cryptexctl-create 1 ,
.Xr cryptexctl-device 1
.Sh HISTORY
Introduced in macOS 11.0
.\" .Sh BUGS            \" Document known, unremedied bugs
