.Dd December 31, 2024
.Dt FTMSTOOL 8
.Os Darwin
.Sh NAME
.Nm ftmstool
.Nd interfaces with
.Nm facetimemessagestore to manage and inspect carrier voicemails, Live Voicemails, and video messages.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
.Nm
is program that can be used to create, read, edit, and delete messages stored by
.Nm facetimemessagestored.
For available commands, use
.Nm ftmstool -h.
.Sh SEE ALSO
.Xr facetimemessagestore 8 ,
.Sh HISTORY
ftmstool first appeared in iOS 17.0, watchOS 10.0, and macOS 16.0
