.Dd January 10, 2024
.Dt FEATUREACCESSAGENT 8
.Os Darwin
.Sh NAME
.Nm FeatureAccessAgent
.Nd iCloud Subscription Status Management
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
FeatureAccessAgent is a user agent that manages iCloud subscription status.
.Sh HISTORY
FeatureAccessAgent first appeared in macOS 15.0.

