.Dd April 03, 2025
.Dt STZ 1
.Os macOS
.Sh NAME
.Nm stz
.Nd Manipulate Streamable Archives
.Sh SYNOPSIS
.Nm
.Cm extract
.Oo
.Op -hash-type Ar hash-type
.Fl -hash-size Ar hash-size-in-bytes
.Fl -hashes-file Pa hashes-file
.Oc
.Pa input-path
.Pa output-path
.Sh DESCRIPTION
This utility may be used to manipulate streamable archives.
.Ss EXTRACT COMMAND
The
.Cm extract
form extracts a streamable archive.
The hash arguments are optional, but if used provide a convenient way to verify the integrity of the archive during extraction.
.Bl -tag -width indent
.It Fl -hash-type Ar hash-type
Set the hash type for verification.
One of:
.Cm MD5
.Cm SHA1
.Cm SHA224
.Cm SHA256
.Cm SHA384
.Cm SHA512
.Pp
The default is
.Cm SHA256 .
.It Fl -hash-size Ar hash-size-in-bytes
Hash the archive's contents over each given byte-sized interval and verify those hashes as the archive is streamed.
.Pp
Disabled if 0 or not specified, otherwise requires
.Fl -hashes-file .
Verify the entire file using a single hash if the string
.Cm full
is given as the hash size.
.It Fl -hashes-file Pa hashes-file
Path to UTF8-encoded file containing the hashes, in order and one line per hash value, of each chunk.
.It Pa input-path
Path to streamable archive to extract.
.It Pa output-path
Path of directory to create into which the contents of the archive will be extracted.
The past must not already exist.
.El
.Sh EXIT STATUS
.Ex -std
.Sh HISTORY
.Nm
first appeared in macOS 15.5.
