.\" Copyright 2024 Apple
.\"
.\" Licensed under the terms set forth in the LICENSE.txt file available at
.\" https://openusd.org/license.
.\"

.ft 1
..

.TH USDEXTRACT
.SH NAME
usdextract - Utility to extract files from .usdz, .glb, and .gltf files
.SH SYNOPSIS
usdextract [inputFiles]
.SH DESCRIPTION
\f[B]usdextract\f[R] is a utility that parses USDZ and GLB/GLTF files, and extracts any documents or resources within them
to a specified directory.


.TP
\f[V]-h\f[R], \f[V]--help\f[R]
Prints out a help message and exits

.TP
\f[V]-o\f[R], \f[V]--out\f[R] [directory]
Extracts the file to the given directory.

.TP
\f[V]--version\f[R]
Display program version information and exits.

.SH EXAMPLES

.TP
\f[V]usdextract input.usdz -o ./extracted\f[R]
Extracts the files from within input.usdz to a directory named "extracted".