.\""Copyright (c) 2024 Apple Inc. All Rights Reserved.
.Dd August 06, 2024
.Dt ANALYTICSAGENT 8
.Os Darwin
.Sh NAME
.Nm analyticsagent
.Nd Diagnostics and Usage
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
analyticsagent is a user daemon that is responsible for collecting/pushing user session diagnostics and usage data to our system daemon, analyticsd.
.Sh SEE ALSO
.Xr analyticsd 8 ,
.Sh HISTORY
analyticsagent first appeared in iOS 18.1 and macOS 15.1
