.\" Copyright (c) 2017 Apple Inc. All rights reserved.
.\"
.\"     @(#)apfsd.8
.Dd August 8, 2017
.Dt APFSD 8
.Os "OS X"
.Sh NAME
.Nm apfsd
.Nd APFS volume manager
.Sh DESCRIPTION
.Nm
is the APFS volume management daemon, it controls volume encryption and decryption, automatic file defragmentation and performs other housekeeping duties as necessary.
.Pp
.Nm
is invoked invoked by launchd(8) when presence of APFS volume is detected.
.Sh FILES
.Pa /System/Library/LaunchDaemons/com.apple.apfsd.plist
.Sh SEE ALSO 
.Xr diskutil 8
