.Dd Feb 1, 2024
.Dt appplaceholdersyncd 8
.Os macOS
.
.Sh NAME
.Nm appplaceholdersyncd
.Nd Agent which syncs app info between devices.
.
.Sh DESCRIPTION
.Nm
This agent exists to support showing icons of apps installed on other devices owned by the user. It syncs
a minimally-sized "placeholder" to provide enough info for registering the app with LaunchServices
and for rendering the app's icon.
.Pp
This command provides a system service and is not intended to be invoked directly.
.
.Sh FILES
.Bl -tag -width com.apple.appplaceholdersyncd.plist -compact
.It Pa /System/Library/LaunchAgents/com.apple.appplaceholdersyncd.plist
.El
.Sh SEE ALSO
.Nm placeholdersynctool
.

