.Dd November 29, 2023
.Dt ATTENTIONAWARENESSD 8
.Os Darwin
.Sh NAME
.Nm attentionawarenessd
.Nd attention awareness daemon
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Handles coordinating and scheduling of attention awareness requests
.Sh HISTORY
First appeared in macOS 15
