.\""Copyright (c) 2022 Apple Computer, Inc. All Rights Reserved.
.Dd July 17, 2022
.Dt CalendarAgentBookmarkMigrationService 8  
.Os macOS
.Sh NAME
.Nm CalendarAgentBookmarkMigrationService
.Nd service for migrating persisted file bookmark data from a legacy agent to its replacement
.Sh DESCRIPTION
.Nm
is a service used during first login of a user after updating from an older OS build to migrate persisted file bookmarks from a legacy agent to its replacement.
.Pp
There are no configuration options to
.Nm , and users should not run 
.Nm  
manually.
