.Dd February 09, 2023
.Dt CIPHERMLD 8
.Os Darwin
.Sh NAME
.Nm ciphermld
.Nd daemon that supports PIR/PEC workflow
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
enables support for PrivateInformationRetrieval (PIR) and PrivateEncryptedCompute (PEC)
.Sh HISTORY
ciphermld fist appeared in macOS 14.0.
