.\" Copyright (c) 2023 Apple Inc. All rights reserved.
.Dd March 20, 2023
.Dt containermanagerd 8
.Os Darwin
.Sh NAME
.Nm containermanagerd
.Nd Application and plug-in containerization management daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
creates, destroys, and otherwise manages containers for applications and their respective plug-ins and works in concert with
.Xr sandbox 7
and
.Xr secinitd 8
to provide application containerization.
It is a classic launch daemon and/or agent managed by
.Xr launchd 8 .
.Pp
Users should not run
.Nm
manually and changing arguments is unsupported.
.Sh FILES
.Bl -bullet
.It
/System/Library/LaunchDaemons/com.apple.containermanagerd.plist
.It
/System/Library/LaunchAgents/com.apple.containermanagerd.plist
.It
/usr/libexec/containermanagerd
.It
~/Library/ContainerManager
.It
~/Library/Caches/com.apple.containermanagerd
.It
~/Library/Containers
.It
~/Library/Daemon Containers
.It
~/Library/GroupContainersAlias
.It
~/Library/Group Containers
.El
.Sh SEE ALSO
.Xr launchd 8 ,
.Xr secinitd 8
.Sh HISTORY
.Nm
was first introduced in macOS 11.
