.\" Copyright (c) 2023 Apple Inc. All rights reserved.
.Dd March 20, 2023
.Dt containermanagerd_system 8
.Os Darwin
.Sh NAME
.Nm containermanagerd_system
.Nd System container directory management daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
creates, destroys, and otherwise manages system containers for application bundles used by
.Xr appinstalld 8 .
 It is a classic launch daemon managed by
.Xr launchd 8 .
.Pp
Users should not run
.Nm
manually and changing arguments is unsupported.
.Sh FILES
.Bl -bullet
.It
/System/Library/LaunchDaemons/com.apple.containermanagerd_system.plist
.It
/usr/libexec/containermanagerd_system
.It
/private/var/root/Library/ContainerManager/System
.It
/private/var/root/Library/Caches/com.apple.containermanagerd/System
.It
/private/var/containers
.El
.Sh SEE ALSO
.Xr appinstalld 8 ,
.Xr launchd 8
.Sh HISTORY
.Nm
was first introduced in macOS 13 and first used in macOS 14.
