.Dd January 9, 2023
.Dt diagnosticextensionsd 8
.Os "macOS"
.Sh NAME
.Nm diagnosticextensionsd
.Nd A background daemon for diagnostics gathering.
.Sh DESCRIPTION
.Nm
gathers diagnostic files for Apple feedback reporting tools.
.Pp
There are no configuration options to \fBdiagnosticextensionsd\fR. Users should not run
.Nm
manually.
