.Dd January 9, 2023
.Dt feedbackd 8
.Os "macOS"
.Sh NAME
.Nm feedbackd
.Nd A background daemon for feedback gathering.
.Sh DESCRIPTION
.Nm
launches feedback gathering tools such as Feedback Assistant.
.Pp
There are no configuration options to \fBfeedbackd\fR. Users should not run
.Nm
manually.
