.\""Copyright (c) 2023 Apple Inc. All Rights Reserved.
.Dd 1/11/14
.Dt findmylocateagent 8
.Os "MacOS"
.Sh NAME
.Nm findmylocateagent
.Nd User agent for the Find My subsystem.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a daemon.
.Pp
There are no configuration options to \fBfindmylocateagent\fR.  Users should not run it manually.
