.\""Copyright (c) 2023 Apple Inc. All Rights Reserved.
.Dd 1/11/14
.Dt FindMyBeaconDaemon 8
.Os "MacOS"
.Sh NAME
.Nm FindMyBeaconDaemon
.Nd Daemon to manage local Mac FindMy beaconing.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a daemon.
.Pp
There are no configuration options to \fBFindMyBeaconDaemon\fR.  Users should not run it manually.
