.\"Copyright (c) 2023 Apple Inc. All Rights Reserved.
.Dd February 14, 2023
.Dt LIQUIDDETECTIOND 8
.Os macOS
.Sh NAME
.Nm liquiddetectiond
.Nd Liquid Detection and Corrosion Mitigation Daemon
.Sh DESCRIPTION
liquiddetectiond runs in the background and collects liquid detection analytics from each USB-C port on the system.
