.Dd $Mdocdate: January 11 2024 $
.Dt managedeventsd 8
.Os macOS
.Sh NAME
.Nm managedeventsd
.Nd Device Management Endpoint Security client daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
monitors disk mount events and responds to mount authentication requests via Endpoint Security API. It will make decisions based on the disk restriction policies from the Remote Management server.
.Sh FILES
.Pa /System/Library/LaunchDaemons/com.apple.devicemanagementclient.managedeventsd.plist
.Sh DIAGNOSTICS
Logging can be viewed via:
log stream --predicate 'process="managedeventsd"'

