.\""Copyright (c) 2024 Apple Computer, Inc. All Rights Reserved.
.Dd October 31, 2024
.Dt milod 8
.Os
.Sh NAME
.Nm milod
.Nd A daemon that provides MicroLocation services.
.Sh DESCRIPTION
.Nm
is a per-user daemon that provides MicroLocation services.
.Pp
There are no configurations to
.Nm , and users should not run
.Nm
manually.
