.\" Copyright (c) 2020 Apple Inc. All rights reserved.
.\"
.\"     @(#)mount_virtiofs.8
.hlm 0
.Dd September 14, 2020
.Dt MOUNT_VIRTIOFS 8
.Os "macOS"
.Sh NAME
.Nm mount_virtiofs
.Nd mount a
.Tn virtio-fs
volume
.Sh SYNOPSIS
.Nm
.Op Fl r
.Op Fl u Ar uid
.Op Fl g Ar gid
.Ar fs_tag
.Ar directory
.Sh DESCRIPTION
The
.Nm
command attaches the
.Tn virtio-fs
file system associated with
.Pa fs_tag
to the global file system namespace at the location indicated by
.Pa directory .
.Pp
The options are as follows:
.Bl -tag -width 12n
.It Fl r
Mount file system as read-only.
.It Fl u
Set the owner of the files in the file system to
.Pa uid .
The
.Pa uid
may be a username or a numeric value.
.It Fl g
Set the group of the files in the file system to
.Pa gid .
The
.Pa gid
may be a group name or a numeric value.


.El
.Sh DIAGNOSTICS
.Ex -std
.Sh SEE ALSO
.Xr mount 2 ,
.Xr unmount 2 ,
.Xr fstab 5 ,
.Xr mount 8 ,
.Xr umount 8
