.Dd Feburary 17, 2022
.Dt NANDTASKSCHEDULER 8
.Os Darwin
.Sh NAME
.Nm NANDTaskScheduler
.Nd Daemon to periodically refresh data on NAND
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
.Nm
periodically runs in background to refresh data stored on NAND
to improve data retention
.Sh HISTORY
first appeared in macOS 13.0
