.Dd February 24, 2023
.Dt RECOVERYUTILD 8
.Os Darwin
.Sh NAME
.Nm recoveryutild
.Nd Accepts recovery-related commands from the recoveryutil CLI tool.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
This daemon receives and executes commands from the recoveryutil CLI tool. For a list of commands, see recoveryutil -h.
.Sh HISTORY
recoveryutild first appeared in macOS Ventura 14.0.
