.\"Copyright (c) 2025 Apple Inc.  All Rights Reserved.
.\"
.Dd August 1, 2025
.Dt SEARCHDIAGNOSE 8
.Os "macOS"
.\"
.\" ----------------------------------------------------------------------------
.Sh NAME
.\" ----------------------------------------------------------------------------
.Nm searchdiagnose
.Nd gathers information to aid in diagnosing Spotlight and Search issues
.\"
.\" ----------------------------------------------------------------------------
.Sh SYNOPSIS
.\" ----------------------------------------------------------------------------
.Nm
.Fl h
.\"
.\" ----------------------------------------------------------------------------
.Sh DESCRIPTION
.\" ----------------------------------------------------------------------------
The
.Nm
tool gathers system and Spotlight information in order to assist Apple when
investigating issues related to Spotlight and Search.
A great deal of information is harvested, spanning system state, system and
Spotlight details.
.\"
.\" --- HARVEST MANIFEST -------------------------------------------------------
.\"
.Ss What Nm Ns " Collects:" Ns
.Bl -bullet -compact
.It
A
.Xr spindump 8
of the system
.It
Several seconds of
.Xr top 1
output
.It
Paths for all files used by Spotlight to contain its database on every volume
.It
All system logs
.It
.Xr sample 1 ,
.Xr heap 1 , and
.Xr spindump 8 of the following processes:
.\"
.\" --- BEGIN PROCESS SUBLIST --------------------------------------------------
.Bl -bullet -offset 3n -compact
.It
.Xr mds 8
.It
mds_stores
.It
mdsync
.It
corespotlightd
.It
Spotlight
.El
.\" --- END PROCESS SUBLIST ----------------------------------------------------
.\"
.It
Spin and crash reports for the following processes, for all local users:
.\"
.\" --- BEGIN PROCESS SUBLIST --------------------------------------------------
.Bl -bullet -offset 3n -compact
.It
.Xr mdfind 1
.It
.Xr mdimport 1
.It
.Xr mdls 1
.It
.Xr mds 8
.It
.Xr mdutil 1
.It
.Xr mdworker 8
.It
corespotlightd
.It
CoreSpotlightService
.It
mdflagwriter
.It
mds_stores
.It
mdsync
.It
mdworker_shared
.It
mdwrite
.It
Spotlight
.It
spotlightknowledged
.El
.\" --- END PROCESS SUBLIST ----------------------------------------------------
.\"
.It
The query text and result quality statistics for recent Spotlight searches.
The actual results of the searches are not gathered
.It
General information about disks and mounted network shares
.It
The path of the last file indexed by each mdworker process on behalf of
Spotlight.
The path of the last file which resulted in a crash of an mdworker process.
In each case, only the path is gathered, not the contents of the file
.It
Spotlight configuration for each volume currently mounted on your system.
This includes the path and size of all files used internally by Spotlight as
well as a listing of paths that are user excluded from indexing
.It
Comprehensive information about internal state of Spotlight
.El
.\"
.\" --- UNHARVEST MANIFEST -----------------------------------------------------
.\"
.Ss What Nm Ns " Doesn't Collect:" Ns
.Bl -bullet -compact
.It
No user data is harvested from any volume
.It
No paths or files found by any search are returned
.It
No database storage or user files are returned
.It
No authentication credentials are harvested from the system
.El
.\"
.\" ----------------------------------------------------------------------------
.Sh OPTIONS
.\" ----------------------------------------------------------------------------
.Bl -hang -compact
.It Fl h
Print full usage.
.El
.\"
.\" ----------------------------------------------------------------------------
.Sh EXIT STATUS
.\" ----------------------------------------------------------------------------
.Nm
exits with status 0 if there were no internal errors encountered during the
diagnostic, or >0 when an error unrelated to external state occurs or unusable
input is provided by the user.
