.\" Copyright (c) 2019-2023 Apple Inc. All rights reserved.
.Dd October 30, 2023
.Dt SYSEXTD 8
.Os Darwin
.Sh NAME
.Nm sysextd
.Nd system extension manager
.Sh DESCRIPTION
.Nm
is a daemon that helps manage system extensions.
It works in coordination with other daemons, with system extensions' host applications, and with the system extensions themselves.
Users should not manually run
.Nm ;
the daemon is automatically started when its services are needed.
.Sh FILES
.Bl -tag
.It Pa /Library/SystemExtensions
System extensions and data managed by the daemon.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr systemextensionsctl 8
.Sh HISTORY
.Nm
was introduced in macOS Catalina 10.15.
