.Dd August 28, 2023
.Dt USBAUDIOD 8
.Os Darwin
.Sh NAME
.Nm usbaudiod
.Nd usbaudiod is a system daemon that runs the USB audio driver.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
usbaudiod implements Apple's USB audio driver for devices that are compliant to the Audio Device Class definitions as published by the USB Implementers Forum. It supports enumeration, streaming and control of USB audio devices through the Core Audio subsystem.
.Sh SEE ALSO
.Xr coreaudiod 8 ,
.Xr audiomxd 8 ,
.Sh HISTORY
usbaudiod first appeared in macOS 15.0 and iOS 18.0.
