.Dd 7/24/2024               \" DATE
.Dt usbpowerd 8  \" Program name and manual section number
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify
.Nm usbpowerd
.Nd Daemon to detect and manage Apple Extra Power Protocol for USB devices
.Sh DESCRIPTION          \" Section Header - required - don't modify
Use
.Xr launchctl 1
to control
.Nm
.
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.It Pa /System/Library/LaunchDaemons/com.apple.usbpowerd.plist
.It Pa /System/Library/Sandbox/Profiles/com.apple.usbpowerd.sb
.El                      \" Ends the list
.Sh SEE ALSO
.Xr launchd 1
.Xr launchctl 1
