.Dd 14/11/2022
.Dt webprivacyd 8
.Os Mac OS X
.Sh NAME
.Nm webprivacyd
.Nd WebPrivacy Daemon
.Sh DESCRIPTION
.Nm
is the system launch agent that periodically updates list data for web tracking protections in the background.
.Pp
There are no configuration options to
.Nm , and users should not run
.Nm
manually.
.Pp
