.Dd 4/2/15
.Dt wifive 8
.Os 
.Sh NAME
.Nm wifive
.Nd Wi-Fi performance and diagnostics utility.
.Sh SYNOPSIS
.Nm
.Cm status
.Nm
.Cm diagnostics
.Op Fl Fl printTestIDs
.Op Fl Fl timeout Aq timeout
.Op Fl t Aq testID
.Nm
.Cm debug
.Op Fl Fl wifi Aq 0,1
.Op Fl Fl bluetooth Aq 0,1
.Op Fl Fl eapol Aq 0,1
.Op Fl Fl dns Aq 0,1
.Nm
.Cm logs
.Op Fl Fl printLogIDs
.Op Fl Fl reason Aq reason
.Op Fl Fl timeout Aq timeout
.Op Fl o Aq outputDirectory
.Op Fl z
.Op Fl l Aq logID
.Nm
.Cm sniff
.Op Fl Fl channel Aq channel
.Fl Fl duration Aq duration
.Op Fl o Aq outputDirectory
.Nm
.Cm events
.Nm
.Cm wifiperf
.Op Fl Fl p2p
.Op Fl Fl artrace
.Op Fl Fl cc Aq milliseconds
.Op Fl Fl powermetrics Aq milliseconds
.Op Fl Fl wifistats Aq seconds
.Pp
.Sh DESCRIPTION
.Nm
is a tool for (1) performing connectivity, configuration, and environment diagnostics tests, (2) querying connection status, (3) configuring various networking-related logging facilities, (4) capturing Wi-Fi traffic, and (5) collecting logs for debugging Wi-Fi-related problems.
.Sh COMMANDS
.Cm status
.Pp
.Dl Displays the current status for Wi-Fi and related components.
.Pp
.Cm diagnostics
.Op Fl Fl printTestIDs
.Op Fl Fl timeout Aq timeout
.Op Fl t Aq testID
.Pp
.Dl Runs diagnostics tests and displays the results.
.Pp
.Cm debug
.Op Fl Fl wifi Aq 0,1
.Op Fl Fl bluetooth Aq 0,1
.Op Fl Fl eapol Aq 0,1
.Op Fl Fl dns Aq 0,1
.Pp
.Dl Enables/disables debug logging for the specified components, or displays the current log configuration if no arguments are specified.
.Pp
.Cm logs
.Op Fl Fl printLogIDs
.Op Fl Fl reason Aq reason
.Op Fl Fl timeout Aq timeout
.Op Fl o Aq outputDirectory
.Op Fl z
.Op Fl l Aq logID
.Pp
.Dl Collects logs and displays the output file path when completed. Specify -z to create a compressed archive.
.Pp
.Dl By default, on OS X devices the output directory is ~/Desktop and on iOS devices the output directory is /Library/Logs/CrashReporter.
.Pp
.Cm sniff
.Op Fl Fl channel Aq channel
.Fl Fl duration Aq duration
.Op Fl o Aq outputDirectory
.Pp
.Dl Starts sniffing Wi-Fi traffic on the specified channel and displays the output file path when completed.
.Pp
.Dl By default, on OS X devices the output directory is ~/Desktop and on iOS devices the output directory is /Library/Logs/CrashReporter.
.Pp
.Cm events
.Pp
.Dl Starts event monitoring and displays the events as they are received.
.Pp
.Dl This command will block indefinitely, ue Ctl-C to stop monitoring events.
.Pp
.Cm wifiperf
.Op Fl Fl p2p
.Op Fl Fl artrace
.Op Fl Fl cc Aq milliseconds
.Op Fl Fl powermetrics Aq milliseconds
.Op Fl Fl wifistats Aq seconds
.Pp
.Dl Starts Wi-Fi performance logging and displays the temporary output directory used for the current session.
.Pp
.Dl This command will block indefinitely, ue Ctl-C to stop the Wi-Fi performance monitoring session.
.Pp
.Sh EXAMPLES
.Pp
Run default set of diagnostic tests:
.Pp
.D1 sudo wifive diagnostics
.Pp
Query debug log configuration:
.Pp
.Dl sudo wifive debug
.Pp
Enable Wi-Fi and EAPOL logging, and disable DNS logging:
.Pp
.Dl sudo wifive debug --eapol 1 --wifi 1 --dns 0
.Pp
Query status information:
.Pp
.Dl sudo wifive status
.Pp
Sniff Wi-Fi traffic on channel 36 for 20 seconds:
.Pp
.Dl sudo wifive sniff --channel 36 --duration 20
.Pp
.Sh AUTHOR
This program and document are maintained by Apple Inc. <wifiperf-help@group.apple.com>
.Sh HISTORY
.Nm
first appeared in Mac OS X 10.12 and iOS 10.
