.\" Copyright (c) 2022-2023 Apple Inc. All rights reserved.
.Dd December 19, 2022
.Dt logd_reporter 8
.Os Darwin
.Sh NAME
.Nm logd_reporter
.Nd unified logging system reporter daemon
.Sh DESCRIPTION
.Nm
is a daemon that periodically observes the behavior of
.Xr logd 8 .
It
should not be directly invoked;
it is only intended for system use.
.Sh SEE ALSO
.Xr logd 8
