.Dd September 19, 2022
.Dt assistant_cdmd 1
.Os
.Sh NAME
.Nm assistant_cdmd,
.Nm CDM/NLX Daemon
.Nd daemon handles Natural Langauge Understanding tasks for Siri and other internal Apple teams.
.Sh DESCRIPTION
.Nm
The assistant_cdmd daemon handles Natural Langauge Understanding tasks for Siri and other internal Apple teams.
