.\""Copyright (c) 2017 Apple Inc. All Rights Reserved.
.Dd 9/13/17
.Dt ckkeyrolld 8
.Os macOS
.Sh NAME
.Nm ckkeyrolld
.Nd "CloudKit Key Rolling Metrics Daemon"
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is the system daemon that rolls and verifies encryption metadata.
.Pp
There are no configuration options to
.Nm . Users should not run
.Nm
manually.
.
.Pp
