.Dd 2/15/2021
.Dt audioclocksyncd 1
.Os Darwin
.Sh NAME
.Nm audioclocksyncd
.Nd clock management and interface for Precision Time Protocol.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
executable is used for the management of Precision Time Protocol (IEEE 1588) clocks and the interface between applications and the clocks.
.Pp
.Nm
is launched automatically by launched as needed on demand and should not be launched manually.
.El
