.Dd October 21, 2024
.Dt betaenrollmentagent 8
.Os "macOS"
.Sh NAME
.Nm betaenrollmentagent
.Nd A background user agent for Seeding.framework.
.Sh DESCRIPTION
.Nm
sets and reads beta enrollment.
.Pp
There are no configuration options to \fBbetaenrollmentagent\fR. Users should not run
.Nm
manually.
