.Dd June 2, 2020
.Dt CRYPTEXCTL-LIST 1
.Os Darwin
.Sh NAME
.Nm cryptexctl list
.Nd list installed cryptexes
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
list
.Op Fl l | -lossy
.Sh DESCRIPTION          \" Section Header - required - don't modify
List the installed cryptexes, either on the host
.Pq if the host has a cryptex management daemon
or on a device specified in the top level command
.Po see
.Xr cryptexctl 1
.Pc .
.Sh OPTIONS
List of flags and their descriptions:
.Bl -tag -width -indent
.It Fl l | -lossy
Fetch the list of installed cryptexes in a lossy way which will not communicate
with
.Xr cryptexd 8 .
Some information may not be available or up to date.
.El
.Sh SEE ALSO
.Xr cryptexctl 1 ,
.Xr cryptexctl-create 1 ,
.Xr cryptexctl-install 1 ,
.Xr cryptexd 8
.Sh HISTORY
Introduced in macOS 11.0
