.Dd June 8, 2020
.Dt CRYPTEXCTL-VERSION 1
.Os Darwin
.Sh NAME
.Nm cryptexctl version
.Nd print the version of a cryptex subsystem component
.Sh SYNOPSIS
.Nm
version
.Op Ar COMPONENT
.Sh DESCRIPTION
Print the version of a cryptex subsystem component.
.Pp
If no
.Ar COMPONENT
is specified, print information about the
.Qq cli
component
.Po
.Xr cryptexctl 1
itself
.Pc .
.Sh OPTIONS
List of components and their descriptions:
.Bl -tag -width -indent
.It Ar cli
The
.Xr cryptexctl 1
tool.
.It Ar library
The
.Xr libcryptex 3
library against which
.Xr cryptexctl 1
is linked.
.It Ar daemon
The
.Xr cryptexd 8
daemon
.Xr cryptexctl 1
is currently communicating with.
.It Ar mobile-device-framework
The MobileDevice framework against which
.Xr cryptexctl 1
is linked.
.El
.Sh EXAMPLES
Display version information about
.Xr cryptexctl 1 :
.Dl % cryptexctl version
.Pp
Display version information about the
.Xr libcryptex 3
library:
.Dl % cryptexctl version library
.Sh SEE ALSO
.Xr cryptexctl 1 ,
.Xr libcryptex 3 ,
.Xr cryptexd 8
.Sh HISTORY
Introduced in macOS 11.0
