.Dd 2/13/24
.Dt transparency-sysdiagnose 1
.Os Darwin
.Sh NAME
.Nm swtransparency-sysdiagnose
.Nd sysdiagnose information for software transparency project
.Sh SYNOPSIS
.Nm gathers sysdiagnose information for transparency
.Sh DESCRIPTION
Gathers sysdiagnose information for transparency
.Sh SEE ALSO
.Xr a transparencyd
