.Dd Sep 19, 2022
.Dt TRUSTCACHECTL 1
.Os
.Sh NAME
.Nm trustcachectl
.Nd Load trust caches and query whether a cd hash is present in a loaded trust cache.
.Sh SYNOPSIS
.Nm
.Ar subcommand
.Op Ar arguments ...
.Sh DESCRIPTION
.Nm
can load new trust caches into the kernel and query whether a given cd hash is present in a loaded trust cache.
.Pp
.Sh SUBCOMMANDS
Note that
.Ar cdhashes
should be 40 hexadecimal characters.
.Bl -tag -width -indent
.It Cm query Ar cdhash
Check if
.Ar cdhash
is in a loaded trust cache.
.It Cm load Ar path
Load the trust cache at
.Ar path .
This tool is only entitled to load the OTA update brain or global install assistant trust cache.
