.Dd Feb 14, 2022
.Dt BackgroundTaskManagementAgent 8
.Os macOS
.
.Sh NAME
.Nm BackgroundTaskManagementAgent
.Nd User agent which manages notifications about background task processes
.
.Sh DESCRIPTION
.Nm
is a per\-user agent that manages notifications of background tasks.
This includes items in System Settings > General > Login Items, items installed with SMAppService or SMLoginItemSetEnabled(), and items from managed device profiles.

This command is not intended to be invoked directly.
.
.Sh FILES
.Pa /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Support/BackgroundTaskManagementAgent.app
.Pp
.Pa /System/Library/LaunchAgents/com.apple.backgroundtaskmanagement.agent.plist
.Pp
.
.Sh SEE ALSO
.Nm btmtool
.
