.\" Copyright (c) 2024 Apple Inc. All rights reserved.
.\"
.\" The contents of this file constitute Original Code as defined in and
.\" are subject to the Apple Public Source License Version 1.1 (the
.\" "License").  You may not use this file except in compliance with the
.\" License.  Please obtain a copy of the License at
.\" http://www.apple.com/publicsource and read it before using this file.
.\"
.\" This Original Code and all software distributed under the License are
.\" distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER
.\" EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES,
.\" INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.  Please see the
.\" License for the specific language governing rights and limitations
.\" under the License.
.\"
.\"     @(#)fskit_agent.8
.Dd March 7, 2024
.Dt FSKIT_AGENT 8
.Os "OS X"
.Sh NAME
.Nm fskit_agent
.Nd FSKit 3rd party extension support agent
.Sh DESCRIPTION
.Nm
is the FSKit per-user FSModule support agent. It
reports FSModule availabilty and enablement to
fskitd per user. It also launches FSModules at the
direction of fskitd.
.Pp
.Sh FILES
.Pa /System/Library/LaunchAgents/com.apple.fskit_agent.plist
