.\" Copyright (c) 2019-2023 Apple Inc. All rights reserved.
.Dd October 30, 2023
.Dt SYSTEMEXTENSIONSCTl 8
.Os Darwin
.Sh NAME
.Nm systemextensionsctl
.Nd examine and manage system extensions
.Sh SYNOPSIS
.Nm
.Cm developer
.Op Cm on \*(Ba off
.Nm
.Cm list
.Nm
.Cm reset
.Sh DESCRIPTION
The
.Nm
program examines and manages system extensions.
.Pp
Users should not run
.Nm
under most circumstances;
this utility is intended for software developers.
.Pp
Its subcommands are:
.Bl -tag
.It Cm developer Op Cm on \*(Ba off
Turn developer mode on and off.
.Pp
When the computer examines a new system extension,
it performs a version check
to see if it is the same as a system extension that is already installed.
When developer mode is on,
this version check is skipped.
.It Cm list
List the system extensions and their state.
States include:
.Bl -tag
.It Li activated enabled
Available for use
.It Li activated waiting for user
Waiting for user approval via System Settings
.It Li terminated waiting for uninstall on reboot
Will be removed at the next computer restart
.El
.It Cm reset
Forcibly reset system extensions.
This removes all system extensions and
clears related state.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr sysextd 8
.Bl -bullet
.It
.Lk https://developer.apple.com/system-extensions/ "System Extensions and DriverKit"
.It
.Lk https://developer.apple.com/documentation/systemextensions/ "System Extensions Framework"
.El
.Sh HISTORY
.Nm
was introduced in macOS Catalina 10.15.
