.Dd October 12, 2021
.Dt BLUETOOTHUSERD 8
.Os Darwin
.Sh NAME
.Nm bluetoothuserd
.Nd Handles user context Bluetooth features 
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
Support Bluetooth features for user specific features that bluetoothd running as root cannot handle
.Sh HISTORY
bluetoothuserd first appeared in macOS 13 and iOS 16.
