.Dd June 2, 2020
.Dt CRYPTEXCTL-LOG 1
.Os Darwin
.Sh NAME
.Nm cryptexctl log
.Nd display or collect logs relevant to the cryptex subsystem
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
log
.Op Fl d | Fl -debug
.Op Fl c | Fl -compact
.Ar <show|stream|collect>
.Oo --
.Op Ar ARGUMENTS-TO-LOG ...
.Oc
.Sh DESCRIPTION          \" Section Header - required - don't modify
Display or collect log messages relevant to the cryptex subsystem from the
.Xr os_log 3
unified logging store. The predicate used collects information logged directly
by
.Xr libcryptex 3
components as well as relevant crashes, and failures in
AppleMobileFileIntegrity, AppleImage4 and MobileDevice.
.Pp
List of flags and their descriptions:
.Bl -tag -width -indent
.It Fl d | Fl -debug
Display debug messages
.Po passes the
.Sq -d
option to
.Xr log 1
.Pc
.It Fl c | Fl -compact
Use the compact log style
.Po
passes the
.Sq --style compact
option to
.Xr log 1
.Pc
.It Ar <show|stream|collect>
The
.Xr log 1
action to perform.
.It --
Delimiter after which arguments to
.Xr log 1
begin
.It Ar ARGUMENTS-TO-LOG
Arguments to be given to
.Xr log 1
.El
.Sh SEE ALSO
.Xr cryptexctl 1 ,
.Xr log 1 ,
.Xr libcryptex 3 ,
.Xr os_log 3 ,
.Xr cryptexd 8
.Sh HISTORY
Introduced in macOS 11.0