.Dd June 8, 2020
.Dt CRYPTEXCTL-HELP 1
.Os Darwin
.Sh NAME
.Nm cryptexctl help
.Nd print some helpful help about cryptexctl or one of its subcommands
.Sh SYNOPSIS
.Nm
help
.Op Ar SUBCOMMAND
.Sh DESCRIPTION
Print some help text about a subcommand, or
.Nm
if no subcommand is provided.
.Sh OPTIONS
List of arguments and their descriptions:
.Bl -tag -width -indent
.It Ar SUBCOMMAND
The subcommand to print help for.
.El
.Sh EXAMPLES
To display help about
.Nm
itself
.Pq including a list of subcommands :
.Dl % cryptexctl help
.Pp
To display help about the
.Ar help
subcommand:
.Dl % cryptexctl help help
.Pp
To display help about the
.Ar list
subcommand:
.Dl % cryptexctl help list
.Sh SEE ALSO
.Xr cryptexctl 1
.Sh HISTORY
Introduced in macOS 11.0
