.Dd June 2, 2020
.Dt CRYPTEXCTL-DUMP-TRUST-CACHE 1
.Os Darwin
.Sh NAME
.Nm cryptexctl dump-trust-cache
.Nd print the content of a trust cache.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
dump-trust-cache
.Op Fl i | Fl -im4p
.Ar TRUST-CACHE-PATH
.Sh DESCRIPTION          \" Section Header - required - don't modify
Print the content of a trust cache. The output will be of the form:
.Pp
.Dl <cdhash> [<occurance count>] <flags>
.Pp
The same code directory hash
.Pq cdhash
may occur multiple times in a single trust cache, and only the number of
occurrences are printed.
.Sh OPTIONS
The following options are accepted by
.Nm
dump-trust-cache
.Pp
.Bl -tag -width -indent
.It Fl i | Fl -im4p
Indicate that the file is a wrapped Image4 payload
.El
.Bl -tag -width -indent
.It Ar TRUST-CACHE-PATH
Path to the trust cache to dump
.El
.Sh SEE ALSO
.Xr codesign 1 ,
.Xr cryptexctl 1 ,
.Xr cryptexctl-create 1 ,
.Xr trustcachectl 1 ,
.Xr cryptexd 8
.Sh HISTORY
Introduced in macOS 11.0
