.Dd November 05, 2024
.Dt SENSINGPREDICTD 8
.Os Darwin
.Sh NAME
.Nm sensingpredictd
.Nd Sensing and Intelligence daemon for AirPods and other Audio Accessories
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
sensingpredictd daemon will be responsible for managing operations that control access to AirPods sensors and configures peripheral input processing.
.Sh HISTORY
sensingpredictd first appeared in macOS 16.0"
