.\""Copyright (c) 2022 Apple Inc. All Rights Reserved.
.Dd $Mdocdate$
.Dt SHAZAM-CUSTOM-CATALOG-EXPORT 1
.Os

.Sh NAME
.Nm shazam custom-catalog export
.Nd Export contents of a custom catalog file

.Sh SYNOPSIS
.Nm
.Op Fl \-input Ar input
.Op Fl \-output Ar output


.Sh DESCRIPTION
.Pp
This command is used to export the contents of a custom catalog file to disk. Running it takes each signature and media items entry of a custom catalog file and writes it to disk. Signature entries are saved as .shazamsignature files and media items are saved as .csv files.

.Sh OPTIONS
.Bl -tag -width indent

.It Fl i,--input Ar input
Path to an existing custom catalog file to be exported to disk.

.It Fl o,--output Ar output
Path to a directory to export the contents of a custom catalog to. Signatures are exported as a .shazamsignature file having the ID of the signature as part of the exported file name. Media items are exported as a .csv file per shazam signature and have the same ID of the signature they are associated with as part of the exported file name.

.Sh SEE ALSO
.Sy shazam-custom-catalog-create(1), shazam-custom-catalog-display(1), shazam-custom-catalog-remove(1)

.Sh NOTES
.Bl -enum
.It
ShazamKit Documentation
.Bd -literal -compact
https://developer.apple.com/shazamkit
.El
