.Dd September 8, 2021
.Dt siriactionsd 8
.Os "macOS"
.Sh NAME
.Nm siriactionsd
.Nd Daemon for the Shortcuts application
.Sh SYNOPSIS
.Nm siriactionsd
.Sh DESCRIPTION
The
.Nm
daemon coordinates running and syncing of shortcuts created in the Shortcuts application, among other Shortcuts-related auxiliary tasks.
.Pp
