.Dd July 10, 2025
.Dt diagnosticspushd 8
.Os "macOS"
.Sh NAME
.Nm diagnosticspushd
.Nd A background daemon for Diagnostics push notifications.
.Sh DESCRIPTION
.Nm
manages push notifications for Apple Support diagnostic flows.
.Pp
There are no configuration options for this service. Users should not run
.Nm
manually.
