.Dd March 14, 2025
.Dt enhancedloggingd 8
.Os "macOS"
.Sh NAME
.Nm enhancedloggingd
.Nd A background daemon for Enhanced Logging.
.Sh DESCRIPTION
.Nm
manages collecting diagnostic files from users reporting issues to Apple Support.
.Pp
There are no configuration options for this service. Users should not run
.Nm
manually.
