.\""Copyright (c) 2016 Apple Computer, Inc. All Rights Reserved.
.Dd November 02, 2016
.Dt intelligentroutingd 8
.Os
.Sh NAME
.Nm intelligentroutingd
.Nd A daemon that provides recommendations based on history patterns.
.Sh DESCRIPTION
.Nm
is a per-user daemon that provides recommendations based on history patterns.
.Pp
There are no configurations to
.Nm , and users should not run
.Nm
manually.
