.Dd January 31, 2025
.Dt MEDIACONTINUITYD 8
.Os Darwin
.Sh NAME
.Nm mediacontinuityd
.Nd MacOS daemon to support continuity features.
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
mediacontinuityd handles coexistience between continuity features
.Sh HISTORY
mediacontinuityd first appeared in macOS 16.0

