.Dd August 15, 2024
.Dt MICACTIVITYD 8
.Os Darwin
.Sh NAME
.Nm micactivityd
.Nd micactivityd is a daemon used for Core Audio related purposes.  
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
micactivityd is a daemon used for Core Audio related purposes.
.Sh SEE ALSO
.Xr coreaudiod 8 ,
.Sh HISTORY
micactivityd first appeared in macOS 15.4
