.Dd May 23, 2024
.Dt SPINANDD 8
.Os Darwin
.Sh NAME
.Nm SPINANDDaemon
.Nd Daemon to store data on dedicated SPI NAND
.Sh SYNOPSIS
Takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
.Nm
Responsible for storing and maintaining data saved on SPINAND memory.
.Sh HISTORY
first appeared in macOS 14.0
