.Dd March 19, 2025
.Dt SWIFTUITRACED 8
.Os Darwin
.Sh NAME
.Nm swiftuitraced
.Nd Collects tracepoints from SwiftUI
.Sh SYNOPSIS
takes no arguments, and users should not launch it manually.
.Sh DESCRIPTION
This daemon orchestrates the process of collecting and writing tracepoints that are coming from SwiftUI layer. It initializes only during tracing
