.\""Copyright (c) 2001-2017 Apple Computer, Inc. All Rights Reserved.
.Dd May 4, 2023
.Dt TRASH 8
.Os "macOS"
.Sh NAME
.Nm trash
.Nd Moves files and directories to the user trash folder
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl Fl help
.Op Fl s
.Op Fl stopOnError
.Op Fl v
.Op Fl Fl verbose
.Ar FILE Op FILE...
.Sh DESCRIPTION
The
.Nm
moves files and directories into the user trash folder.
The options are as follows:
.Bl -tag -width "---------"
.It Fl h | Fl Fl help
display usage information for the tool and exit
.It Fl v | Fl Fl verbose
display more verbose status
.It Fl s | Fl Fl stopOnError
exit with an error if any move to a trash folder fails
.El
.Sh EXAMPLES
In a directory with a file named "Foo.txt" and a directory "Bar",
.Pp
.Nm
Foo.txt Bar
.Pp
moves the file and directory into the user's trash folder, if it exists and permissions allow the items to be moved into the user's trash folder.
.Sh HISTORY
First appeared in macOS 15.0
